title: Walsh
logo:  # you can add own logo.
description: Research Assistant at The Alan Turing Institute
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


# Author Settings
author:
  name: James Walsh
  image: '/assets/img/james_walsh.jpg'
  job: PhD Student, University of Cambridge
#   bio: <strong>Research Assistant</strong> at <a href="https://www.turing.ac.uk/people/researchers/james-walsh">The Alan Turing Institute</a> <br /><br /> Working on <a href="https://www.turing.ac.uk/research/research-projects/physics-informed-statistical-learning-battery-lifetime">physics-informed machine learning</a><br />supervised by <a href="https://warwick.ac.uk/fac/sci/statistics/staff/academic-research/damoulas/">Dr Theo Damoulas</a> 
  bio: James Walsh is a final year PhD student working within the <a href="https://ukfires.org/james-walsh/">Use Less research group</a> at the <a href="https://www.fibe-cdt.eng.cam.ac.uk/staff/james-walsh">University of Cambridge</a>. His work focuses on evaluating early-stage design decisions for sustainability of industrial installations. He is supervised by <a href="https://www.uselessgroup.org/about-us/current-people/dr-cyrille-dunant">Dr Cyrille Dunant</a>, advised by <a href="https://www.uselessgroup.org/about-us/current-people/dr-andre-cabrera-serrenho">Dr André Cabrera Serrenho</a>, and funded by <a href="https://www.ukri.org/councils/epsrc/">EPSRC</a> &#38; <a href="https://www.aveva.com/">AVEVA</a> via <a href="https://www.fibe-cdt.eng.cam.ac.uk/">FIBE2</a>. He supervises 2nd year undergraduate mechanics for his College and is faculty at <a href="https://fdl.ai/">FDL Heliolab</a>.
  email: hello@walsh.dev


# Contact links
contact:
  - name: Google Scholar
    link: https://scholar.google.com/citations?view_op=list_works&hl=en&user=gyScxvoAAAAJ
  - name: LinkedIn
    link: https://uk.linkedin.com/in/jejwalsh
  - name: GitHub
    link: https://github.com/dead-water


# Comment Section (Disqus)
# disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


# Google Analytics
google-analytics: UA-158621574-1


# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-sitemap
  - jekyll/tagging

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag-page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed


# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
